namespace Jaguar.Core.Models;

public class ProjectState
{
    public Guid Id { get; set; }
    public string UserGoal { get; set; } // "Create a Python stock trading bot"
    public List<string> HighLevelPlan { get; set; } // Steps 1-10 generated by Orchestrator
    public Dictionary<string, string> SharedMemory { get; set; } // Key-Value store for global facts (e.g., "API_KEY", "FilePaths")
    public TaskStatus Status { get; set; }
}